language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
    - SYMFONY_VERSION="^3.1"
    - SYMFONY_VERSION="^2.7"
    - SYMFONY_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION="dev-master"

before_script:
    - composer self-update # Update composer as travis is not updating it.
    - >
        composer require --dev \
          symfony/console:${SYMFONY_VERSION} \
          symfony/process:${SYMFONY_VERSION} \
          symfony/yaml:${SYMFONY_VERSION} \
          symfony/config:${SYMFONY_VERSION} \
          symfony/filesystem:${SYMFONY_VERSION} \
          symfony/finder:${SYMFONY_VERSION}

    - phpenv rehash

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=/vendor ./
  - vendor/bin/phpunit --coverage-clover=coverage.clover -d zend.enable_gc=0
  - ./syncfs.phar

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
