language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="2.5.*"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
    - composer self-update # Update composer as travis is not updating it.
    - >
        composer require --dev \
          symfony/console:${SYMFONY_VERSION} \
          symfony/process:${SYMFONY_VERSION} \
          symfony/yaml:${SYMFONY_VERSION} \
          symfony/config:${SYMFONY_VERSION} \
          symfony/filesystem:${SYMFONY_VERSION} \
          symfony/finder:${SYMFONY_VERSION}

#    - composer install --dev
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash
    - git clone git://github.com/opensky/Symfony2-coding-standard.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/Symfony2

script:
  - phpcs --standard=Symfony2 --ignore=/vendor ./
  - vendor/bin/phpunit --coverage-clover=coverage.clover -d zend.enable_gc=0
  - vendor/bin/box build
  - ./syncfs.phar

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover