#!/usr/bin/env php
<?php
// set to run indefinitely if needed
set_time_limit(0);

// installed via composer?
if (file_exists($a = __DIR__ . '/../../../../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__ . '/../vendor/autoload.php';
}

$libDir = __DIR__ . '/../lib/SyncFS';

// import the Symfony Console Application
use Symfony\Component\Console\Application;
use SyncFS\AutoLoader;

$app        = new Application('SyncFS', '@package_version@');
$autoLoader = new AutoLoader($libDir);

$app->addCommands($autoLoader->getCommands());
$app->run();