#!/usr/bin/env php
<?php
// set to run indefinitely if needed
set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use SyncFS\Command\SyncCommand;
use SyncFS\Command\InitCommand;
use Symfony\Component\Console\Application;

$app = new Application('SyncFS', '@package_version@');

$app->add(new SyncCommand());
$app->add(new InitCommand());
$app->run();